[package]
name = "pie_to_bytes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-vm = { version = '1.0.0-rc1' }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
